"""Lightweight destinations and search copy, independent of widget creation.

Control routes are explicit so existing deep links can request a control and
build its owning page. Search metadata mirrors the page's tile/field copy.
"""
CONTROL_DESTINATIONS = {'mcp_page': 'mcp',
 'mcp_view': 'mcp',
 'mcp_history_tile': 'mcp',
 'backup_page': 'backup',
 'backup_create_tile': 'backup',
 'backup_restore_tile': 'backup',
 'backup_schedule_tile': 'backup',
 'hf_policy_combo': 'downloads',
 'auto_paste_tile': 'general',
 'auto_paste_check': 'general',
 'copy_clipboard_tile': 'general',
 'copy_clipboard_check': 'general',
 'minimize_tray_tile': 'general',
 'minimize_tray_check': 'general',
 'update_check_tile': 'general',
 'update_check_check': 'general',
 'update_notify_tile': 'general',
 'update_notify_check': 'general',
 'ui_theme_combo': 'general',
 'ui_theme_tile': 'general',
 'ui_font_scale_combo': 'general',
 'ui_font_scale_tile': 'general',
 'accessibility_status': 'general',
 'accessibility_setup_button': 'general',
 '_accessibility_timer': 'general',
 'audio_device_combo': 'recording',
 'audio_device_tile': 'recording',
 'recording_retention_combo': 'recording',
 'recording_retention_tile': 'recording',
 'max_recordings_label': 'recording',
 'max_recordings_spinbox': 'recording',
 'max_recordings_mb_label': 'recording',
 'max_recordings_mb_spinbox': 'recording',
 'recordings_usage_label': 'recording',
 'streaming_enabled_tile': 'recording',
 'streaming_enabled_check': 'recording',
 'streaming_font_size_label': 'recording',
 'streaming_font_size_spinbox': 'recording',
 'transcript_cleanup_tile': 'cleanup',
 'transcript_cleanup_check': 'cleanup',
 'cleanup_model_tile': 'cleanup',
 'cleanup_prompt_edit': 'cleanup',
 'cleanup_prompt_tile': 'cleanup',
 'cleanup_prompt_edit_btn': 'cleanup',
 'cleanup_prompt_reset_btn': 'cleanup',
 'cleanup_profiles_panel': 'cleanup_profiles',
 'cleanup_rules_gate_tile': 'cleanup_rules',
 'open_cleanup_btn': 'cleanup_rules',
 'cleanup_rules_composer_tile': 'cleanup_rules',
 'cleanup_rule_input': 'cleanup_rules',
 'cleanup_rule_mic_btn': 'cleanup_rules',
 'cleanup_rule_add_btn': 'cleanup_rules',
 'cleanup_rule_activity': 'cleanup_rules',
 'cleanup_rule_status': 'cleanup_rules',
 'cleanup_rules_library_tile': 'cleanup_rules',
 'cleanup_rules_count': 'cleanup_rules',
 'cleanup_rules_list': 'cleanup_rules',
 '_rule_glow': 'cleanup_rules',
 'cleanup_rules_empty': 'cleanup_rules',
 'cleanup_rule_edit_btn': 'cleanup_rules',
 'cleanup_rule_delete_btn': 'cleanup_rules',
 'meeting_model_tile': 'meeting_intelligence',
 'meeting_agent_picker': 'meeting_intelligence',
 'meeting_past_recall_tile': 'meeting_intelligence',
 'meeting_past_recall_check': 'meeting_intelligence',
 'meeting_context_folder_tile': 'meeting_intelligence',
 'meeting_context_folder_check': 'meeting_intelligence',
 'meeting_context_folder_path': 'meeting_intelligence',
 'typesafe_key_notice': 'meeting_fast',
 'open_typesafe_key_btn': 'meeting_fast',
 'typesafe_enabled_tile': 'meeting_fast',
 'typesafe_enabled_check': 'meeting_fast',
 'typesafe_topic_shift_tile': 'meeting_fast',
 'typesafe_topic_shift_check': 'meeting_fast',
 'typesafe_voice_commands_tile': 'meeting_fast',
 'typesafe_voice_commands_check': 'meeting_fast',
 'typesafe_feature_tiles': 'meeting_fast',
 'typesafe_switch_route_btn': 'meeting_fast',
 'typesafe_route_tile': 'meeting_fast',
 'typesafe_route_bar': 'meeting_fast',
 'typesafe_route_test_btn': 'meeting_fast',
 'typesafe_route_status': 'meeting_fast',
 'typesafe_destination_label': 'meeting_fast',
 'meeting_end_redecode_tile': 'meeting_after',
 'meeting_end_redecode_check': 'meeting_after',
 'meeting_end_polish_tile': 'meeting_after',
 'meeting_end_polish_check': 'meeting_after',
 'meeting_end_report_tile': 'meeting_after',
 'meeting_end_report_check': 'meeting_after',
 'meeting_review_tile': 'meeting_after',
 'meeting_review_check': 'meeting_after',
 'meeting_review_sensitivity': 'meeting_after',
 'meeting_report_ribbon_tile': 'meeting_after',
 'meeting_report_brief_tile': 'meeting_after',
 'meeting_report_signal_tile': 'meeting_after',
 'meeting_report_ribbon_check': 'meeting_after',
 'meeting_report_brief_check': 'meeting_after',
 'meeting_report_signal_check': 'meeting_after',
 'meeting_report_views_title': 'meeting_after',
 'meeting_report_views_info': 'meeting_after',
 'meeting_report_views_hint': 'meeting_after',
 'meeting_bind_combo': 'meeting_dashboard',
 'meeting_bind_tile': 'meeting_dashboard',
 'meeting_bind_warning': 'meeting_dashboard',
 'meeting_port_spinbox': 'meeting_dashboard',
 'meeting_port_tile': 'meeting_dashboard',
 'api_key_combo': 'api_keys',
 'api_key_credential_tile': 'api_keys',
 'api_key_status_icon': 'api_keys',
 'api_key_status': 'api_keys',
 'api_key_uses_caption': 'api_keys',
 'api_key_entry_tile': 'api_keys',
 'api_key_store_caption': 'api_keys',
 'api_key_edit': 'api_keys',
 'api_key_show_button': 'api_keys',
 'api_key_save_button': 'api_keys',
 'api_key_test_button': 'api_keys',
 'api_key_remove_button': 'api_keys',
 '_hotkey_instruction': 'hotkeys',
 '_hotkey_instruction_text': 'hotkeys',
 'record_mode_combo': 'hotkeys',
 'meeting_redecode_coverage_guard_tile': 'advanced',
 'meeting_redecode_coverage_guard_check': 'advanced',
 'developer_mode_tile': 'advanced',
 'developer_mode_check': 'advanced'}

MODEL_CONTROL_DESTINATIONS = {'engine_combo': 'voice_model',
 'engine_caption': 'voice_model',
 'ondemand_whisper_picker': 'voice_model',
 'ondemand_whisper_field': 'voice_model',
 'speech_controls': 'voice_model',
 'api_model_combo': 'voice_model',
 'api_model_field': 'voice_model',
 'engine_inventory_title': 'voice_model',
 'engine_inventory_row': 'voice_model',
 'engine_inventory_label': 'voice_model',
 'speech_download_button': 'voice_model',
 'text_model_picker': 'cleanup',
 'cleanup_reasoning_combo': 'cleanup',
 'cleanup_model_tile': 'cleanup',
 'meeting_source_combo': 'meeting_voice',
 'meeting_whisper_picker': 'meeting_voice',
 'meeting_local_model_field': 'meeting_voice',
 'meeting_remote_controls': 'meeting_voice',
 'meeting_remote_test': 'meeting_voice',
 'meeting_remote_status': 'meeting_voice',
 'meeting_runtime_label': 'meeting_voice',
 'meeting_language_combo': 'meeting_voice',
 'meeting_speaker_id_combo': 'meeting_voice',
 '_speaker_id_backend_previous': 'meeting_voice',
 'speaker_id_status': 'meeting_voice',
 'meeting_agent_picker': 'meeting_intelligence',
 'meeting_model_title': 'meeting_intelligence',
 'meeting_model_picker': 'meeting_intelligence',
 'meeting_agent_core_combo': 'meeting_intelligence',
 'meeting_model_tile': 'meeting_intelligence',
 'device_combo': 'runtime',
 'compute_combo': 'runtime'}

PAGE_SEARCH_FIELDS = {'mcp': [('mcp_history_tile',
                             "Share this computer's history through the paired host's MCP",
                             'Allow assistants to search saved dictations and meetings and read '
                             'transcripts and insights on this computer while OpenWhisper is running.')],
 'general': [('auto_paste_tile', 'Paste into the active window', ''),
             ('copy_clipboard_tile',
              'Copy to the clipboard',
              'Keeps the transcript on the clipboard when auto-paste is off or unavailable. A '
              'successful paste restores what was there before.'),
             ('minimize_tray_tile',
              'Minimize to the system tray on close',
              'Closing the window keeps OpenWhisper running in the tray, so hotkeys and recording '
              'stay available.'),
             ('update_check_tile',
              'Check for updates automatically',
              'Looks for new OpenWhisper releases in the background. Nothing is installed without '
              'your approval.'),
             ('update_notify_tile',
              'Notify me about updates',
              'Opens the update dialog when a newer release is found. Requires automatic checks.'),
             ('ui_theme_tile', 'Theme', 'Dark, light, or match your operating system.'),
             ('ui_font_scale_tile',
              'Font size',
              'Text size in windows and dialogs. The live preview overlay has its own under '
              'Recording.')],
 'recording': [('audio_device_tile',
                'Input device',
                'The microphone used for dictation and meetings.'),
               ('recording_retention_tile',
                'Keep recordings',
                'Keep a set number of recordings or cap the recordings folder size. The oldest '
                'audio files are deleted automatically once the limit is passed; the newest '
                'recording is always kept. Transcription history text is kept separately.'),
               ('streaming_enabled_tile',
                'Real-time transcription preview',
                'Shows text as you speak on the near-cursor overlay. Nemotron uses native '
                'streaming; Parakeet transcribes short audio chunks with the loaded model; Local '
                'Whisper uses a separate tiny.en preview model. The final transcript uses your '
                'selected model and follows the General paste and clipboard settings.')],
 'cleanup': [('transcript_cleanup_tile',
              'Clean up transcripts with AI',
              'Runs the selected chat model on each dictated transcript after transcription, '
              "together with your learned rules. The provider's key lives under API keys."),
             ('cleanup_prompt_tile',
              'Cleanup prompt',
              'Instructions the model follows when rewriting a transcript.'),
             ('cleanup_model_tile',
              'Chat model',
              'The provider and model that rewrite each dictation. Cleanup profiles use it too. '
              "The provider's key lives under API keys."),
             ('cleanup_reasoning_combo', 'Thinking level', '')],
 'cleanup_rules': [('cleanup_rules_gate_tile',
                    'AI cleanup is off',
                    'Learned rules only apply when cleanup runs. Teaching and editing stay locked '
                    'until you turn on Clean up transcripts with AI.'),
                   ('cleanup_rules_composer_tile',
                    'Teach a new rule',
                    'Type or dictate an instruction in your own words. Your AI cleanup model '
                    "rewrites it as a clear rule, and you review it before it's saved."),
                   ('cleanup_rules_library_tile',
                    'Your rules',
                    'Select a rule or double-click it to edit. Every rule applies to AI cleanup, '
                    'and to profiles set to also apply learned rules.')],
 'meeting_intelligence': [('meeting_past_recall_tile',
                           'Search past transcripts',
                           'Off by default. The agent can look up names and prior decisions from '
                           'stored meetings. Excerpts leave this machine the same way the current '
                           'transcript does.'),
                          ('meeting_context_folder_tile',
                           'Search a knowledge folder',
                           'Choose a local folder, for example an Obsidian vault. Matched excerpts '
                           'leave this machine the same way the current transcript does. Images, '
                           'audio, and video are not read.'),
                          ('meeting_model_tile',
                           'Chat model',
                           "Pi or OpenCode SDK runs live cards, the note taker, polish, "
                           'summaries, and the final report with this endpoint and your API key.'),
                          ('meeting_agent_core_combo', 'Agent core', '')],
 'meeting_fast': [('typesafe_key_notice', 'No TypeSafe API key', ''),
                  ('typesafe_route_tile',
                   'Jev connection',
                   'Run fast judgments with a TypeSafe key, or with your OpenRouter key through '
                   'OpenRouter. Same Jev model either way. Test sends one tiny judgment.'),
                  ('typesafe_enabled_tile',
                   'TypeSafe fast judgments (Experimental)',
                   'Off by default. Answers narrow yes/no questions about a minute of transcript '
                   'in about 0.2 s; never writes text. Key: API keys → TypeSafe or OpenRouter.'),
                  ('typesafe_topic_shift_tile',
                   'Semantic topic changes (Experimental)',
                   'Fire early checkpoints on a judged topic change instead of word overlap. '
                   'Doubled precision on human-labelled meetings; falls back to word overlap when '
                   'no answer arrives.'),
                  ('typesafe_voice_commands_tile',
                   'Spoken instructions (Experimental)',
                   '"Note taker, mark that as a decision", "…add an action item", "…put that in '
                   'the notes", "…new topic: budget". Only segments naming the assistant are '
                   'judged. Recap updates notes; "replace X with Y" applies a reversible '
                   'transcript correction.')],
 'meeting_after': [('meeting_end_redecode_tile',
                    'Re-transcribe the full recording',
                    'After End, recut the continuous session audio on longer quiet gaps and run '
                    'Whisper again. Live capture is unchanged.'),
                   ('meeting_end_polish_tile',
                    'Clean up the transcript with the LLM',
                    'Rewrites the finished transcript for readability. Needs AI insights on for '
                    'the meeting.'),
                   ('meeting_end_report_tile',
                    'Write the final report',
                    'Topic, summary, and cards, generated once live captions finish. Needs AI '
                    'insights on for the meeting.'),
                   ('meeting_review_tile',
                    'Review uncertain insights at the end (Experimental)',
                    'Optional, for new meetings. Sends relevant transcript excerpts, speaker '
                    'names, and insights to TypeSafe to identify ambiguities. Start with the three '
                    'highest-priority questions, then choose Review more to see the rest. No audio '
                    'is sent. Requires AI insights, TypeSafe fast judgments on the Fast judgments '
                    'page, and a TypeSafe or OpenRouter API key (Settings → API keys).'),
                   ('meeting_report_ribbon_tile',
                    'Ribbon',
                    'Timeline walk. Adds timeline beats and polished minutes, which is the main '
                    'token cost.'),
                   ('meeting_report_brief_tile',
                    'Brief',
                    'One-page editorial summary. Reuses the same cards as Signal.'),
                   ('meeting_report_signal_tile',
                    'Signal',
                    'One-screen glance. Reuses the same cards as Brief.')],
 'meeting_dashboard': [('meeting_bind_tile',
                        'Who can open the dashboard',
                        'Localhost keeps the live dashboard on this computer. Sharing serves it to '
                        'other devices on your local network.'),
                       ('meeting_port_tile',
                        'Dashboard port',
                        'Automatic lets the meeting server pick a free port each session. Pick a '
                        'fixed port only if you need a stable link.')],
 'api_keys': [('api_key_credential_tile',
               'Credential',
               'Choose the provider whose key you want to save or test.'),
              ('api_key_entry_tile', 'Add or replace a key', '')],
 'advanced': [('meeting_redecode_coverage_guard_tile',
               'Keep the live transcript if re-transcription is much shorter',
               "Reject a re-transcription with fewer than 80% of the live transcript's words. Word "
               'count does not measure accuracy. Applies after End and when retrying saved '
               'meetings. Off by default.'),
              ('developer_mode_tile',
               'Developer mode',
               'Unlocks a Load demo meeting control on the Meeting Mode tab. The demo opens the '
               'dashboard with a fake transcript so you can test end-of-meeting cleanup and the '
               'final report without recording a real meeting.')],
 'voice_model': [('ondemand_whisper_picker', 'Model', ''),
                 ('api_model_combo', 'Model', ''),
                 ('engine_combo', 'Recording engine', '')],
 'meeting_voice': [('meeting_whisper_picker', 'Meeting speech model', ''),
                   ('meeting_source_combo', 'Speech engine', ''),
                   ('meeting_language_combo', 'Spoken language', ''),
                   ('meeting_speaker_id_combo', 'Speaker identification', '')],
 'runtime': [('device_combo', 'Device', ''), ('compute_combo', 'Quantization', '')],
 'backup': [('backup_create_tile', 'Back up local data',
             'Save local settings, transcription history, meeting data, and optionally recordings.'),
            ('backup_restore_tile', 'Inspect and restore',
             'Review a backup archive before staging a restore and restart.'),
            ('backup_schedule_tile', 'Schedule',
             'Automatic local backups: off, daily, or weekly; set destination and retention count.')]}

PAGE_HELP_TEXT = {'voice_model': ['For dictation previews, Nemotron uses native streaming; Parakeet transcribes '
                 'short audio chunks with the loaded model; Local Whisper uses a separate tiny.en '
                 'model. The final transcript uses your selected model. Nemotron and Moonshine '
                 'provide native live previews in Meeting Mode.'],
 'runtime': ['Parakeet, Nemotron, Moonshine, and Qwen3-ASR set their device on Dictation → Voice '
             'model. Downloaded models and optional components are managed in Downloads.']}


def merge_page_module(key: str, module) -> None:
    """Route a page module's controls and search copy like a built-in page's.

    Settings hands each page module over when it imports it, so this file
    never imports page code itself.
    """
    for name in getattr(module, "CONTROL_ATTRS", ()):
        CONTROL_DESTINATIONS[name] = key
    PAGE_SEARCH_FIELDS[key] = list(getattr(module, "SEARCH_FIELDS", ()))
