"""Explicit OpenCode protocol routes, from /docs/{go,zen}/#endpoints (2026-09-06).

Limits below are conservative client budgets, not advertised model context sizes.
The live catalog determines availability; new IDs require a reviewed route.
"""
from dataclasses import asdict, dataclass
from threading import Lock

_ollama_specs = {}
_ollama_lock = Lock()


def remember_ollama_spec(base_url, model, capabilities, context_window=4096):
    # Cache only non-secret capabilities; endpoint snapshots preserve them for reruns.
    spec = TextModelSpec(tools='tools' in capabilities, reasoning='thinking' in capabilities,
                         context_window=context_window, max_output_tokens=min(4096, context_window // 2))
    with _ollama_lock:
        _ollama_specs[(base_url, model)] = spec



@dataclass(frozen=True)
class TextModelSpec:
    protocol: str = "chat"
    tools: bool = True
    context_window: int = 32768
    max_output_tokens: int = 4096
    reasoning: bool = False
    reasoning_format: str = ""
    pi_compat: dict | None = None
    thinking_levels: dict | None = None

    def to_dict(self):
        return asdict(self)


_ROUTES = {
    "opencode_go": {
        "responses": (
            "grok-4.6", "gpt-5.6-luna", "muse-spark-1.3-contributor",
            "muse-spark-1.2-contributor",
        ),
        "chat": (
            "glm-5.3-flash", "glm-5.3", "glm-5.2",
            "glm-5.1", "kimi-k3", "kimi-k2.7-code",
            "kimi-k2.6", "longcat-2.0", "deepseek-v4-pro",
            "deepseek-v4-flash", "deepseek-v4-flash-vision-exp", "mimo-v2.5",
            "mimo-v2.5-pro", "hy4-preview", "hy3",
            "omen-alpha",
        ),
        "anthropic": (
            "minimax-m3", "minimax-m2.7", "minimax-m2.5",
            "qwen3.8-max", "qwen3.8-flash", "qwen3.7-max",
            "qwen3.7-plus", "qwen3.6-plus",
        ),
    },
    "opencode_zen": {
        "responses": (
            "gpt-6-astra", "gpt-5.6-sol", "gpt-5.6-terra",
            "gpt-5.6-luna", "gpt-5.5", "gpt-5.5-pro",
            "gpt-5.4", "gpt-5.4-pro", "gpt-5.4-mini",
            "gpt-5.4-nano", "gpt-5.3-codex", "gpt-5.3-codex-spark",
            "gpt-5.2", "gpt-5.2-codex", "gpt-5.1",
            "gpt-5.1-codex", "gpt-5.1-codex-max", "gpt-5.1-codex-mini",
            "gpt-5", "gpt-5-codex", "gpt-5-nano",
            "grok-4.6", "grok-4.5", "grok-build-0.1",
            "muse-spark-1.3", "muse-spark-1.2", "muse-spark-1.3-contributor-free",
        ),
        "anthropic": (
            "claude-fable-5-1", "claude-fable-5", "claude-opus-5",
            "claude-opus-4-8", "claude-opus-4-7", "claude-opus-4-6",
            "claude-opus-4-5", "claude-sonnet-5", "claude-sonnet-4-6",
            "claude-sonnet-4-5", "claude-haiku-4-5", "qwen3.7-max",
            "qwen3.7-plus", "qwen3.6-plus", "qwen3.5-plus",
        ),
        "google": (
            "gemini-3.8-flash", "gemini-3.7-flash", "gemini-3.6-flash",
            "gemini-3.5-flash", "gemini-3.5-flash-lite", "gemini-3.1-pro",
            "gemini-3-flash",
        ),
        "chat": (
            "deepseek-v4-pro", "deepseek-v4-flash", "deepseek-v4-flash-vision-exp",
            "minimax-m3", "minimax-m2.7", "minimax-m2.5",
            "glm-5.3-flash", "glm-5.3", "glm-5.2",
            "glm-5.1", "glm-5", "kimi-k2.5",
            "kimi-k2.6", "kimi-k2.7-code", "kimi-k3",
            "big-pickle", "mimo-v2.5-free", "ling-3.0-flash-fin-free",
            "nemotron-3-ultra-free", "nemotron-3.5-lightning-free",
        ),
    },
}


def model_spec(profile, model: str) -> TextModelSpec:
    if not model or not model.strip():
        raise ValueError("Choose a text model first.")
    saved = getattr(profile, "model_metadata", None)
    if saved and saved.get("model") == model:
        return spec_from_mapping(saved)
    if profile.kind == "ollama":
        with _ollama_lock:
            return _ollama_specs.get((profile.base_url, model), TextModelSpec(context_window=4096, max_output_tokens=2048))
    if profile.kind in _ROUTES:
        for protocol, models in _ROUTES[profile.kind].items():
            if model in models:
                return TextModelSpec(protocol=protocol, **_CAPABILITIES.get(profile.kind, {}).get(model, {}))
        raise ValueError(f"{model} has no supported API route for {profile.name}. Choose a supported model.")
    if profile.kind == "groq" and any(word in model.lower() for word in ("whisper", "tts", "orpheus", "guard", "compound")):
        raise ValueError("Choose a Groq text-generation model.")
    if profile.kind == "groq":
        return TextModelSpec()
    return TextModelSpec(reasoning=profile.kind in ("openai", "openrouter"),
                         context_window=131072, max_output_tokens=16384)


def spec_from_mapping(raw: dict) -> TextModelSpec:
    protocol = raw.get("protocol", "chat")
    if protocol not in ("chat", "responses", "anthropic", "google"):
        raise ValueError("Unsupported saved text protocol.")
    return TextModelSpec(
        protocol=protocol, tools=raw.get("tools", True) is True,
        context_window=max(1024, min(2000000, int(raw.get("context_window", 32768)))),
        max_output_tokens=max(16, min(131072, int(raw.get("max_output_tokens", 4096)))),
        reasoning=raw.get("reasoning", False) is True,
        reasoning_format=raw.get("reasoning_format", "") if raw.get("reasoning_format", "") in ("openai", "deepseek", "zai") else "",
        pi_compat=raw.get("pi_compat") if isinstance(raw.get("pi_compat"), dict) else None,
        thinking_levels=raw.get("thinking_levels") if isinstance(raw.get("thinking_levels"), dict) else None,
    )


# Capability snapshot from the installed pi-ai provider catalog; output is capped for meeting turns.
_CAPABILITIES = {'opencode_go': {'minimax-m3': {'context_window': 1000000, 'max_output_tokens': 16384, 'reasoning': True},
                 'qwen3.7-max': {'context_window': 1000000, 'max_output_tokens': 16384, 'reasoning': True},
                 'qwen3.7-plus': {'context_window': 1000000, 'max_output_tokens': 16384, 'reasoning': True},
                 'qwen3.8-max': {'context_window': 1000000, 'max_output_tokens': 16384, 'reasoning': True},
                 'deepseek-v4-flash': {'context_window': 1000000,
                                       'max_output_tokens': 16384,
                                       'reasoning': True,
                                       'reasoning_format': 'deepseek',
                                       'pi_compat': {'supportsStore': False,
                                                     'supportsDeveloperRole': False,
                                                     'maxTokensField': 'max_tokens',
                                                     'requiresReasoningContentOnAssistantMessages': True,
                                                     'thinkingFormat': 'deepseek'},
                                       'thinking_levels': {'minimal': None,
                                                           'low': None,
                                                           'medium': None,
                                                           'high': 'high',
                                                           'max': 'max'}},
                 'deepseek-v4-pro': {'context_window': 1000000,
                                     'max_output_tokens': 16384,
                                     'reasoning': True,
                                     'reasoning_format': 'deepseek',
                                     'pi_compat': {'supportsStore': False,
                                                   'supportsDeveloperRole': False,
                                                   'maxTokensField': 'max_tokens',
                                                   'requiresReasoningContentOnAssistantMessages': True,
                                                   'thinkingFormat': 'deepseek'},
                                     'thinking_levels': {'minimal': None,
                                                         'low': None,
                                                         'medium': None,
                                                         'high': 'high',
                                                         'max': 'max'}},
                 'glm-5.1': {'context_window': 202752,
                             'max_output_tokens': 16384,
                             'reasoning': True,
                             'pi_compat': {'supportsStore': False,
                                           'supportsDeveloperRole': False,
                                           'maxTokensField': 'max_tokens'}},
                 'glm-5.2': {'context_window': 1000000,
                             'max_output_tokens': 16384,
                             'reasoning': True,
                             'pi_compat': {'supportsStore': False,
                                           'supportsDeveloperRole': False,
                                           'maxTokensField': 'max_tokens'},
                             'thinking_levels': {'off': None,
                                                 'minimal': None,
                                                 'low': None,
                                                 'medium': None,
                                                 'high': 'high',
                                                 'xhigh': None,
                                                 'max': 'max'}},
                 'hy3': {'context_window': 256000,
                         'max_output_tokens': 16384,
                         'reasoning': True,
                         'pi_compat': {'supportsStore': False,
                                       'supportsDeveloperRole': False,
                                       'maxTokensField': 'max_tokens'},
                         'thinking_levels': {'off': 'none',
                                             'minimal': None,
                                             'low': 'low',
                                             'medium': None,
                                             'high': 'high',
                                             'xhigh': None,
                                             'max': None}},
                 'kimi-k2.6': {'context_window': 262144,
                               'max_output_tokens': 16384,
                               'reasoning': True,
                               'reasoning_format': 'deepseek',
                               'pi_compat': {'supportsStore': False,
                                             'supportsDeveloperRole': False,
                                             'thinkingFormat': 'deepseek',
                                             'supportsReasoningEffort': False,
                                             'maxTokensField': 'max_tokens',
                                             'supportsLongCacheRetention': False},
                               'thinking_levels': {'minimal': None, 'low': None, 'medium': None}},
                 'kimi-k2.7-code': {'context_window': 262144,
                                    'max_output_tokens': 16384,
                                    'reasoning': True,
                                    'pi_compat': {'supportsStore': False,
                                                  'supportsDeveloperRole': False,
                                                  'maxTokensField': 'max_tokens'}},
                 'kimi-k3': {'context_window': 1048576,
                             'max_output_tokens': 16384,
                             'reasoning': True,
                             'pi_compat': {'supportsStore': False,
                                           'supportsDeveloperRole': False,
                                           'maxTokensField': 'max_tokens'},
                             'thinking_levels': {'off': None,
                                                 'minimal': None,
                                                 'low': None,
                                                 'medium': None,
                                                 'high': None,
                                                 'xhigh': None,
                                                 'max': 'max'}},
                 'mimo-v2.5': {'context_window': 1000000,
                               'max_output_tokens': 16384,
                               'reasoning': True,
                               'pi_compat': {'supportsStore': False,
                                             'supportsDeveloperRole': False,
                                             'maxTokensField': 'max_tokens'}},
                 'mimo-v2.5-pro': {'context_window': 1048576,
                                   'max_output_tokens': 16384,
                                   'reasoning': True,
                                   'pi_compat': {'supportsStore': False,
                                                 'supportsDeveloperRole': False,
                                                 'maxTokensField': 'max_tokens'}},
                 'minimax-m2.7': {'context_window': 204800,
                                  'max_output_tokens': 16384,
                                  'reasoning': True,
                                  'pi_compat': {'supportsStore': False,
                                                'supportsDeveloperRole': False,
                                                'maxTokensField': 'max_tokens'}},
                 'qwen3.6-plus': {'context_window': 1000000,
                                  'max_output_tokens': 16384,
                                  'reasoning': True,
                                  'reasoning_format': 'qwen',
                                  'pi_compat': {'supportsStore': False,
                                                'supportsDeveloperRole': False,
                                                'thinkingFormat': 'qwen',
                                                'maxTokensField': 'max_tokens'}},
                 'gpt-5.6-luna': {'context_window': 1050000,
                                  'max_output_tokens': 16384,
                                  'reasoning': True,
                                  'reasoning_format': 'openai',
                                  'pi_compat': {'sessionAffinityFormat': 'openai-nosession'},
                                  'thinking_levels': {'off': None,
                                                      'minimal': None,
                                                      'low': 'low',
                                                      'medium': 'medium',
                                                      'high': 'high',
                                                      'xhigh': 'xhigh',
                                                      'max': 'max'}},
                 'grok-4.5': {'context_window': 500000,
                              'max_output_tokens': 16384,
                              'reasoning': True,
                              'pi_compat': {'sessionAffinityFormat': 'openai-nosession'},
                              'thinking_levels': {'off': None,
                                                  'minimal': None,
                                                  'low': 'low',
                                                  'medium': 'medium',
                                                  'high': 'high',
                                                  'xhigh': None,
                                                  'max': None}}},
 'opencode_zen': {'claude-fable-5': {'context_window': 1000000,
                                     'max_output_tokens': 16384,
                                     'reasoning': True,
                                     'pi_compat': {'forceAdaptiveThinking': True},
                                     'thinking_levels': {'off': None, 'xhigh': 'xhigh', 'max': 'max'}},
                  'claude-haiku-4-5': {'context_window': 200000,
                                       'max_output_tokens': 16384,
                                       'reasoning': True},
                  'claude-opus-4-5': {'context_window': 200000,
                                      'max_output_tokens': 16384,
                                      'reasoning': True},
                  'claude-opus-4-6': {'context_window': 1000000,
                                      'max_output_tokens': 16384,
                                      'reasoning': True,
                                      'pi_compat': {'forceAdaptiveThinking': True},
                                      'thinking_levels': {'max': 'max'}},
                  'claude-opus-4-7': {'context_window': 1000000,
                                      'max_output_tokens': 16384,
                                      'reasoning': True,
                                      'pi_compat': {'forceAdaptiveThinking': True,
                                                    'supportsTemperature': False},
                                      'thinking_levels': {'xhigh': 'xhigh', 'max': 'max'}},
                  'claude-opus-4-8': {'context_window': 1000000,
                                      'max_output_tokens': 16384,
                                      'reasoning': True,
                                      'pi_compat': {'forceAdaptiveThinking': True,
                                                    'supportsTemperature': False},
                                      'thinking_levels': {'xhigh': 'xhigh', 'max': 'max'}},
                  'claude-opus-5': {'context_window': 1000000,
                                    'max_output_tokens': 16384,
                                    'reasoning': True,
                                    'pi_compat': {'forceAdaptiveThinking': True,
                                                  'supportsTemperature': False},
                                    'thinking_levels': {'xhigh': 'xhigh', 'max': 'max'}},
                  'claude-sonnet-4': {'context_window': 200000,
                                      'max_output_tokens': 16384,
                                      'reasoning': True},
                  'claude-sonnet-4-5': {'context_window': 200000,
                                        'max_output_tokens': 16384,
                                        'reasoning': True},
                  'claude-sonnet-4-6': {'context_window': 1000000,
                                        'max_output_tokens': 16384,
                                        'reasoning': True,
                                        'pi_compat': {'forceAdaptiveThinking': True},
                                        'thinking_levels': {'max': 'max'}},
                  'claude-sonnet-5': {'context_window': 1000000,
                                      'max_output_tokens': 16384,
                                      'reasoning': True,
                                      'pi_compat': {'forceAdaptiveThinking': True},
                                      'thinking_levels': {'xhigh': 'xhigh', 'max': 'max'}},
                  'qwen3.5-plus': {'context_window': 262144, 'max_output_tokens': 16384, 'reasoning': True},
                  'qwen3.6-plus': {'context_window': 262144, 'max_output_tokens': 16384, 'reasoning': True},
                  'gemini-3-flash': {'context_window': 1048576,
                                     'max_output_tokens': 16384,
                                     'reasoning': True,
                                     'thinking_levels': {'off': None}},
                  'gemini-3.1-pro': {'context_window': 1048576,
                                     'max_output_tokens': 16384,
                                     'reasoning': True,
                                     'thinking_levels': {'off': None,
                                                         'minimal': None,
                                                         'low': 'LOW',
                                                         'medium': None,
                                                         'high': 'HIGH'}},
                  'gemini-3.5-flash': {'context_window': 1048576,
                                       'max_output_tokens': 16384,
                                       'reasoning': True,
                                       'thinking_levels': {'off': None}},
                  'gemini-3.5-flash-lite': {'context_window': 1048576,
                                            'max_output_tokens': 16384,
                                            'reasoning': True,
                                            'thinking_levels': {'off': None}},
                  'gemini-3.6-flash': {'context_window': 1048576,
                                       'max_output_tokens': 16384,
                                       'reasoning': True,
                                       'thinking_levels': {'off': None}},
                  'big-pickle': {'context_window': 200000,
                                 'max_output_tokens': 16384,
                                 'reasoning': True,
                                 'pi_compat': {'supportsStore': False,
                                               'supportsDeveloperRole': False,
                                               'maxTokensField': 'max_tokens'}},
                  'deepseek-v4-flash': {'context_window': 1000000,
                                        'max_output_tokens': 16384,
                                        'reasoning': True,
                                        'pi_compat': {'supportsStore': False,
                                                      'supportsDeveloperRole': False,
                                                      'maxTokensField': 'max_tokens',
                                                      'supportsLongCacheRetention': False,
                                                      'requiresReasoningContentOnAssistantMessages': True},
                                        'thinking_levels': {'off': None,
                                                            'minimal': None,
                                                            'low': None,
                                                            'medium': None,
                                                            'high': 'high',
                                                            'xhigh': None,
                                                            'max': 'max'}},
                  'deepseek-v4-flash-free': {'context_window': 200000,
                                             'max_output_tokens': 16384,
                                             'reasoning': True,
                                             'pi_compat': {'supportsStore': False,
                                                           'supportsDeveloperRole': False,
                                                           'maxTokensField': 'max_tokens',
                                                           'requiresReasoningContentOnAssistantMessages': True},
                                             'thinking_levels': {'off': None,
                                                                 'minimal': None,
                                                                 'low': None,
                                                                 'medium': None,
                                                                 'high': 'high',
                                                                 'xhigh': None,
                                                                 'max': 'max'}},
                  'deepseek-v4-pro': {'context_window': 1000000,
                                      'max_output_tokens': 16384,
                                      'reasoning': True,
                                      'pi_compat': {'supportsStore': False,
                                                    'supportsDeveloperRole': False,
                                                    'maxTokensField': 'max_tokens',
                                                    'supportsLongCacheRetention': False,
                                                    'requiresReasoningContentOnAssistantMessages': True},
                                      'thinking_levels': {'off': None,
                                                          'minimal': None,
                                                          'low': None,
                                                          'medium': None,
                                                          'high': 'high',
                                                          'xhigh': None,
                                                          'max': 'max'}},
                  'glm-5': {'context_window': 204800,
                            'max_output_tokens': 16384,
                            'reasoning': True,
                            'pi_compat': {'supportsStore': False,
                                          'supportsDeveloperRole': False,
                                          'maxTokensField': 'max_tokens'}},
                  'glm-5.1': {'context_window': 204800,
                              'max_output_tokens': 16384,
                              'reasoning': True,
                              'pi_compat': {'supportsStore': False,
                                            'supportsDeveloperRole': False,
                                            'maxTokensField': 'max_tokens'}},
                  'glm-5.2': {'context_window': 1000000,
                              'max_output_tokens': 16384,
                              'reasoning': True,
                              'pi_compat': {'supportsStore': False,
                                            'supportsDeveloperRole': False,
                                            'maxTokensField': 'max_tokens'},
                              'thinking_levels': {'off': None,
                                                  'minimal': None,
                                                  'low': None,
                                                  'medium': None,
                                                  'high': 'high',
                                                  'xhigh': None,
                                                  'max': 'max'}},
                  'grok-build-0.1': {'context_window': 256000,
                                     'max_output_tokens': 16384,
                                     'reasoning': True,
                                     'pi_compat': {'supportsStore': False,
                                                   'supportsDeveloperRole': False,
                                                   'supportsReasoningEffort': False,
                                                   'maxTokensField': 'max_tokens'},
                                     'thinking_levels': {'off': None,
                                                         'minimal': None,
                                                         'low': None,
                                                         'medium': None}},
                  'kimi-k2.5': {'context_window': 262144,
                                'max_output_tokens': 16384,
                                'reasoning': True,
                                'pi_compat': {'supportsStore': False,
                                              'supportsDeveloperRole': False,
                                              'maxTokensField': 'max_tokens',
                                              'supportsLongCacheRetention': False}},
                  'kimi-k2.6': {'context_window': 262144,
                                'max_output_tokens': 16384,
                                'reasoning': True,
                                'reasoning_format': 'deepseek',
                                'pi_compat': {'supportsStore': False,
                                              'supportsDeveloperRole': False,
                                              'thinkingFormat': 'deepseek',
                                              'supportsReasoningEffort': False,
                                              'maxTokensField': 'max_tokens',
                                              'supportsLongCacheRetention': False}},
                  'kimi-k2.7-code': {'context_window': 262144,
                                     'max_output_tokens': 16384,
                                     'reasoning': True,
                                     'pi_compat': {'supportsStore': False,
                                                   'supportsDeveloperRole': False,
                                                   'maxTokensField': 'max_tokens'}},
                  'kimi-k3': {'context_window': 1048576,
                              'max_output_tokens': 16384,
                              'reasoning': True,
                              'pi_compat': {'supportsStore': False,
                                            'supportsDeveloperRole': False,
                                            'maxTokensField': 'max_tokens'},
                              'thinking_levels': {'off': None,
                                                  'minimal': None,
                                                  'low': None,
                                                  'medium': None,
                                                  'high': None,
                                                  'xhigh': None,
                                                  'max': 'max'}},
                  'laguna-s-2.1-free': {'context_window': 256000,
                                        'max_output_tokens': 16384,
                                        'reasoning': True,
                                        'pi_compat': {'supportsStore': False,
                                                      'supportsDeveloperRole': False,
                                                      'maxTokensField': 'max_tokens'},
                                        'thinking_levels': {'off': None,
                                                            'minimal': None,
                                                            'low': 'low',
                                                            'medium': 'medium',
                                                            'high': 'high',
                                                            'xhigh': None,
                                                            'max': None}},
                  'ling-3.0-flash-free': {'context_window': 262144,
                                          'max_output_tokens': 16384,
                                          'reasoning': True,
                                          'pi_compat': {'supportsStore': False,
                                                        'supportsDeveloperRole': False,
                                                        'maxTokensField': 'max_tokens'},
                                          'thinking_levels': {'off': None,
                                                              'minimal': None,
                                                              'low': 'low',
                                                              'medium': 'medium',
                                                              'high': 'high',
                                                              'xhigh': None,
                                                              'max': None}},
                  'longcat-2.0-free': {'context_window': 1000000,
                                       'max_output_tokens': 16384,
                                       'reasoning': True,
                                       'pi_compat': {'supportsStore': False,
                                                     'supportsDeveloperRole': False,
                                                     'maxTokensField': 'max_tokens'}},
                  'mimo-v2.5-free': {'context_window': 200000,
                                     'max_output_tokens': 16384,
                                     'reasoning': True,
                                     'pi_compat': {'supportsStore': False,
                                                   'supportsDeveloperRole': False,
                                                   'maxTokensField': 'max_tokens'}},
                  'minimax-m2.5': {'context_window': 204800,
                                   'max_output_tokens': 16384,
                                   'reasoning': True,
                                   'pi_compat': {'supportsStore': False,
                                                 'supportsDeveloperRole': False,
                                                 'maxTokensField': 'max_tokens'}},
                  'minimax-m2.7': {'context_window': 204800,
                                   'max_output_tokens': 16384,
                                   'reasoning': True,
                                   'pi_compat': {'supportsStore': False,
                                                 'supportsDeveloperRole': False,
                                                 'maxTokensField': 'max_tokens',
                                                 'supportsLongCacheRetention': False}},
                  'minimax-m3': {'context_window': 512000,
                                 'max_output_tokens': 16384,
                                 'reasoning': True,
                                 'pi_compat': {'supportsStore': False,
                                               'supportsDeveloperRole': False,
                                               'maxTokensField': 'max_tokens'}},
                  'nemotron-3-ultra-free': {'context_window': 1000000,
                                            'max_output_tokens': 16384,
                                            'reasoning': True,
                                            'pi_compat': {'supportsStore': False,
                                                          'supportsDeveloperRole': False,
                                                          'maxTokensField': 'max_tokens'}},
                  'north-mini-code-free': {'context_window': 256000,
                                           'max_output_tokens': 16384,
                                           'reasoning': True,
                                           'pi_compat': {'supportsStore': False,
                                                         'supportsDeveloperRole': False,
                                                         'maxTokensField': 'max_tokens'},
                                           'thinking_levels': {'off': 'none',
                                                               'minimal': None,
                                                               'low': None,
                                                               'medium': None,
                                                               'high': 'high',
                                                               'xhigh': None,
                                                               'max': None}},
                  'gpt-5': {'context_window': 400000,
                            'max_output_tokens': 16384,
                            'reasoning': True,
                            'reasoning_format': 'openai',
                            'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                          'supportsOpenAIGrammarTools': True},
                            'thinking_levels': {'off': None,
                                                'minimal': 'minimal',
                                                'low': 'low',
                                                'medium': 'medium',
                                                'high': 'high',
                                                'xhigh': None,
                                                'max': None}},
                  'gpt-5-codex': {'context_window': 400000,
                                  'max_output_tokens': 16384,
                                  'reasoning': True,
                                  'reasoning_format': 'openai',
                                  'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                                'supportsOpenAIGrammarTools': True},
                                  'thinking_levels': {'off': None,
                                                      'minimal': None,
                                                      'low': 'low',
                                                      'medium': 'medium',
                                                      'high': 'high',
                                                      'xhigh': None,
                                                      'max': None}},
                  'gpt-5-nano': {'context_window': 400000,
                                 'max_output_tokens': 16384,
                                 'reasoning': True,
                                 'reasoning_format': 'openai',
                                 'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                               'supportsOpenAIGrammarTools': True},
                                 'thinking_levels': {'off': None,
                                                     'minimal': 'minimal',
                                                     'low': 'low',
                                                     'medium': 'medium',
                                                     'high': 'high',
                                                     'xhigh': None,
                                                     'max': None}},
                  'gpt-5.1': {'context_window': 400000,
                              'max_output_tokens': 16384,
                              'reasoning': True,
                              'reasoning_format': 'openai',
                              'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                            'supportsOpenAIGrammarTools': True},
                              'thinking_levels': {'off': None,
                                                  'minimal': None,
                                                  'low': 'low',
                                                  'medium': 'medium',
                                                  'high': 'high',
                                                  'xhigh': None,
                                                  'max': None}},
                  'gpt-5.1-codex': {'context_window': 400000,
                                    'max_output_tokens': 16384,
                                    'reasoning': True,
                                    'reasoning_format': 'openai',
                                    'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                                  'supportsOpenAIGrammarTools': True},
                                    'thinking_levels': {'off': None,
                                                        'minimal': None,
                                                        'low': 'low',
                                                        'medium': 'medium',
                                                        'high': 'high',
                                                        'xhigh': None,
                                                        'max': None}},
                  'gpt-5.1-codex-max': {'context_window': 400000,
                                        'max_output_tokens': 16384,
                                        'reasoning': True,
                                        'reasoning_format': 'openai',
                                        'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                                      'supportsOpenAIGrammarTools': True},
                                        'thinking_levels': {'off': None,
                                                            'minimal': None,
                                                            'low': 'low',
                                                            'medium': 'medium',
                                                            'high': 'high',
                                                            'xhigh': 'xhigh',
                                                            'max': None}},
                  'gpt-5.1-codex-mini': {'context_window': 400000,
                                         'max_output_tokens': 16384,
                                         'reasoning': True,
                                         'reasoning_format': 'openai',
                                         'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                                       'supportsOpenAIGrammarTools': True},
                                         'thinking_levels': {'off': None,
                                                             'minimal': None,
                                                             'low': 'low',
                                                             'medium': 'medium',
                                                             'high': 'high',
                                                             'xhigh': None,
                                                             'max': None}},
                  'gpt-5.2': {'context_window': 400000,
                              'max_output_tokens': 16384,
                              'reasoning': True,
                              'reasoning_format': 'openai',
                              'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                            'supportsOpenAIGrammarTools': True},
                              'thinking_levels': {'off': None,
                                                  'minimal': None,
                                                  'low': 'low',
                                                  'medium': 'medium',
                                                  'high': 'high',
                                                  'xhigh': 'xhigh',
                                                  'max': None}},
                  'gpt-5.2-codex': {'context_window': 400000,
                                    'max_output_tokens': 16384,
                                    'reasoning': True,
                                    'reasoning_format': 'openai',
                                    'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                                  'supportsOpenAIGrammarTools': True},
                                    'thinking_levels': {'off': None,
                                                        'minimal': None,
                                                        'low': 'low',
                                                        'medium': 'medium',
                                                        'high': 'high',
                                                        'xhigh': 'xhigh',
                                                        'max': None}},
                  'gpt-5.3-codex': {'context_window': 400000,
                                    'max_output_tokens': 16384,
                                    'reasoning': True,
                                    'reasoning_format': 'openai',
                                    'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                                  'supportsOpenAIGrammarTools': True},
                                    'thinking_levels': {'off': None,
                                                        'minimal': None,
                                                        'low': 'low',
                                                        'medium': 'medium',
                                                        'high': 'high',
                                                        'xhigh': 'xhigh',
                                                        'max': None}},
                  'gpt-5.4': {'context_window': 272000,
                              'max_output_tokens': 16384,
                              'reasoning': True,
                              'reasoning_format': 'openai',
                              'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                            'supportsOpenAIGrammarTools': True},
                              'thinking_levels': {'off': None,
                                                  'minimal': None,
                                                  'low': 'low',
                                                  'medium': 'medium',
                                                  'high': 'high',
                                                  'xhigh': 'xhigh',
                                                  'max': None}},
                  'gpt-5.4-mini': {'context_window': 400000,
                                   'max_output_tokens': 16384,
                                   'reasoning': True,
                                   'reasoning_format': 'openai',
                                   'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                                 'supportsOpenAIGrammarTools': True},
                                   'thinking_levels': {'off': None,
                                                       'minimal': None,
                                                       'low': 'low',
                                                       'medium': 'medium',
                                                       'high': 'high',
                                                       'xhigh': 'xhigh',
                                                       'max': None}},
                  'gpt-5.4-nano': {'context_window': 400000,
                                   'max_output_tokens': 16384,
                                   'reasoning': True,
                                   'reasoning_format': 'openai',
                                   'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                                 'supportsOpenAIGrammarTools': True},
                                   'thinking_levels': {'off': None,
                                                       'minimal': None,
                                                       'low': 'low',
                                                       'medium': 'medium',
                                                       'high': 'high',
                                                       'xhigh': 'xhigh',
                                                       'max': None}},
                  'gpt-5.4-pro': {'context_window': 1050000,
                                  'max_output_tokens': 16384,
                                  'reasoning': True,
                                  'reasoning_format': 'openai',
                                  'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                                'supportsOpenAIGrammarTools': True},
                                  'thinking_levels': {'off': None,
                                                      'minimal': None,
                                                      'low': None,
                                                      'medium': 'medium',
                                                      'high': 'high',
                                                      'xhigh': 'xhigh',
                                                      'max': None}},
                  'gpt-5.5': {'context_window': 1050000,
                              'max_output_tokens': 16384,
                              'reasoning': True,
                              'reasoning_format': 'openai',
                              'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                            'supportsOpenAIGrammarTools': True},
                              'thinking_levels': {'off': None,
                                                  'minimal': None,
                                                  'low': 'low',
                                                  'medium': 'medium',
                                                  'high': 'high',
                                                  'xhigh': 'xhigh',
                                                  'max': None}},
                  'gpt-5.5-pro': {'context_window': 1050000,
                                  'max_output_tokens': 16384,
                                  'reasoning': True,
                                  'reasoning_format': 'openai',
                                  'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                                'supportsOpenAIGrammarTools': True},
                                  'thinking_levels': {'off': None,
                                                      'minimal': None,
                                                      'low': None,
                                                      'medium': 'medium',
                                                      'high': 'high',
                                                      'xhigh': 'xhigh',
                                                      'max': None}},
                  'gpt-5.6-luna': {'context_window': 1050000,
                                   'max_output_tokens': 16384,
                                   'reasoning': True,
                                   'reasoning_format': 'openai',
                                   'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                                 'supportsOpenAIGrammarTools': True},
                                   'thinking_levels': {'off': None,
                                                       'minimal': None,
                                                       'low': 'low',
                                                       'medium': 'medium',
                                                       'high': 'high',
                                                       'xhigh': 'xhigh',
                                                       'max': 'max'}},
                  'gpt-5.6-sol': {'context_window': 1050000,
                                  'max_output_tokens': 16384,
                                  'reasoning': True,
                                  'reasoning_format': 'openai',
                                  'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                                'supportsOpenAIGrammarTools': True},
                                  'thinking_levels': {'off': None,
                                                      'minimal': None,
                                                      'low': 'low',
                                                      'medium': 'medium',
                                                      'high': 'high',
                                                      'xhigh': 'xhigh',
                                                      'max': 'max'}},
                  'gpt-5.6-terra': {'context_window': 1050000,
                                    'max_output_tokens': 16384,
                                    'reasoning': True,
                                    'reasoning_format': 'openai',
                                    'pi_compat': {'sessionAffinityFormat': 'openai-nosession',
                                                  'supportsOpenAIGrammarTools': True},
                                    'thinking_levels': {'off': None,
                                                        'minimal': None,
                                                        'low': 'low',
                                                        'medium': 'medium',
                                                        'high': 'high',
                                                        'xhigh': 'xhigh',
                                                        'max': 'max'}},
                  'grok-4.5': {'context_window': 500000,
                               'max_output_tokens': 16384,
                               'reasoning': True,
                               'pi_compat': {'sessionAffinityFormat': 'openai-nosession'},
                               'thinking_levels': {'off': None,
                                                   'minimal': None,
                                                   'low': 'low',
                                                   'medium': 'medium',
                                                   'high': 'high',
                                                   'xhigh': None,
                                                   'max': None}}}}
